const backgroundText = `DESHIL HOLLES EAMUS. DESHIL HOLLES EAMUS. DESHIL HOLES Eamus.

Send us, bright one, light one, Horhorn, quickening and wombfruit. Send us, bright one, light one, Horhorn, quickening and wombfruit. Send us bright one, light one, Horhorn, quickening and wombfruit.

Hoopsa, boyaboy, hoopsa! Hoopsa, hoyaboy, hoopsa! Hoopsa, boyaboy, hoopsa.

Universally that person's acumen is esteemed very little perceptive concerning whatsoever matters are being held as most profitable by mortals with sapience endowed to be studied who is ignorant of that which the most in doctrine erudite and certainly by reason of that in them high mind's ornament deserving of veneration constantly maintain when by general consent they affirm that other circumstances being equal by no exterior splendour is the prosperity of a nation more efficaciously asserted than by the measure of how far forward may have progressed the tribute of its solicitude for that proliferent continuance which of evils the original if it be absent when fortunately present constitutes the certain sign of omnipollent nature's incorrupted benefaction. For who is there who anything of some significance has apprehended but is conscious that that exterior splendour may be the surface of a downwardtending lutulent reality or on the contrary anyone so is there inilluminated as not to perceive that as no nature's boon can contend against the bounty of increase so it behoves every most just citizen to become the exhortator and admonisher of his semblables and to tremble lest what had in the past been by the nation excellently commenced might be in the future not with similar excellence accomplished if an inverecund habit shall have gradually traduced the honourable by ancestors transmitted customs to that thither of profundity that that one was audacious excessively who would have the hardihood to rise affirming that no more odious offence can for anyone be than to oblivious neglect to consign that evangel simultaneously command and promise which on all mortals with prophecy of abundance or with diminution's menace that exalted of reiteratedly procreating function ever irrevocably enjoined?

It is not why therefore we shall wonder if, as the best historians relate, among the Celts, who nothing that was not in its nature admirable admired, the art of medicine shall have been highly honoured. Not to speak of hostels, leperyards, sweating chambers, plaguegraves, their greatest doctors, the O'Shiels, the O'Hickeys, the O'Lees, have sedulously set down the divers methods by which the sick and the relapsed found again health whether the malady had been trembling withering or loose boyconnell flux. Certainly in every public work which in it anything of gravity contains preparation should be with importance commensurate and therefore a plan was by them adopted (whether by having preconsidered or as the maturation of experience it is difficult in being said which the discrepant opinions of subsequent inquirers are not up to the present congrued to render manifest) whereby maternity was so far from all accident possibility removed that whatever care the patient in that allhardest of woman hour chiefly required and not solely for the copiously opulent but also for her who not being sufficiently moneyed scarcely and often not even scarcely could subsist valiantly and for an inconsiderable emolument was provided.

To her nothing already then and thenceforward was anyway able to be molestful for this chiefly felt all citizens except with proliferent mothers prosperity at all not to can be and as they had received eternity gods mortals generation to befit them her beholding, when the case was so having itself, parturient in vehicle the reward carrying desire immense among all one another was impelling on of her to be received into that domicile. O thing of prudent nation not merely in being seen but also even in being related worthy of being praised that they her by anticipation went seeing mother, that she by them suddenly to be about to be cherished had been begun she felt!

Before born babe bliss had. Within womb won he worship. Whatever in that one case done commodiously done was. A couch by midwives attended with wholesome food reposeful cleanest swaddles as though forthbringing were now done and by wise foresight set: but to this no less of what drugs there is need and surgical implements which are pertaining to her case not omitting aspect of all very distracting spectacles in various latitudes by our terrestrial orb offered together with images, divine and human, the cogitation of which by sejunct females is to tumescence conducive or eases issue in the high sunbright wellbuilt fair home of mothers when, ostensibly far gone and reproductitive, it is come by her thereto to lie in, her term up.

Some man that wayfaring was stood by housedoor at night's oncoming. Of Israel's folk was that man that on earth wandering far had fared. Stark ruth of man his errand that him lone led till that house.

Of that house A. Horne is lord. Seventy beds keeps he there teeming mothers are wont that they lie for to thole and bring forth bairns hale so God's angel to Mary quoth. Watchers they there walk, white sisters in ward sleepless. Smarts they still sickness soothing: in twelve moons thrice an hundred. Truest bedthanes they twain are, for Horne holding wariest ward.

In ward wary the watcher hearing come that man mild-hearted eft rising with swire ywimpled to him her gate wide undid. Lo, levin leaping lightens in eyeblink Ireland's westward welkin! Full she dread that God the Wreaker all mankind would fordo with water for his evil sins. Christ's rood made she on breastbone and him drew that he would rathe infare under her thatch. That man her will wotting worthful went in Horne's house.

Loth to irk in Horne's hall hat holding the seeker stood. On her stow he ere was living with dear wife and lovesome daughter that then over land and seafloor nine year had long outwandered. Once her in townhithe meeting he to her bow had not doffed. Her to forgive now he craved with good ground of her allowed that that of him swiftseen face, hers, so young then had looked. Light swift her eyes kindled, bloom of blushes his word winning.

As her eyes then ongot his weeds swart therefor sorrow she feared. Glad after she was that ere adread was. Her he asked if O'Hare Doctor tidings sent from far coast and she with grameful sigh him answered that O'Hare Doctor in heaven was. Sad was the man that word to hear that him so heavied in bowels ruthful. All she there told him, ruing death for friend so young, algate sore unwilling God's rightwiseness to withsay. She said that he had a fair sweet death through God His goodness with masspriest to be shriven, holy housel and sick men's oil to his limbs. The man then right earnest asked the nun of which death the dead man was died and the nun answered him and said that he was died in Mona island through bellycrab three year agone come Childermas and she prayed to God the Allruthful to have his dear soul in his undeathliness. He heard her sad words, in held hat sad staring. So stood they there both awhile in wanhope, sorrowing one with other.

Therefore, everyman, look to that last end that is thy death and the dust that gripeth on every man that is born of woman for as he came naked forth from his mother's womb so naked shall he wend him at the last for to go as he came.

The man that was come into the house then spoke to the nursingwoman and he asked her how it fared with the woman that lay there in childbed. The nursingwoman answered him and said that that woman was in throes now full three days and that it would be a hard birth unneth to bear but that now in a little it would be. She said thereto that she had seen many births of women but never was none so hard as was that woman's birth. Then she set it forth all to him that time was had lived nigh that house. The man hearkened to her words for he felt with wonder women's woe in the travail that they have of motherhood and he wondered to look on her face that was a young face for any man to see but yet was she left after long years a handmaid. Nine twelve bloodflows chiding her childless.

And whiles they spake the door of the castle was opened and there nighed them a mickle noise as of many that sat there at meat. And there came against the place as they stood a young learning knight yclept Dixon. And the traveller Leopold was couth to him sithen it had happed that they had had ado each with other in the house of misericord where this learning knight lay by cause the traveller Leopold came there to be healed for he was sore wounded in his breast by a spear wherewith a horrible and dreadful dragon was smitten him for which he did do make a salve of volatile salt and chrism as much as he might suffice. And he said now that he should go into that castle for to make merry with them that were there. And the traveller Leopold said that he should go otherwhither for he was a man of cautels and a subtle. Also the lady was of his avis and reproved the learning knight though she trowed well that the traveller had said thing that was false for his subtility. But the learning knight would not hear say nay nor do her mandement ne have him in aught contrarious to his list and he said how it was a marvellous castle. And the traveller Leopold went into the castle for to rest him for a space being sore of limb after many marches environing in divers lands and sometimes venery.

And in the castle was set a board that was of the birchwood of Finlandy and it was upheld by four dwarfmen of that country but they durst not move for enchantment. And on this board were frightful swords and knives that are made in a great cavern by swinking demons out of white flames that they fix in the horns of buffalos and stags that there abound marvellously. And there were vessels that are wrought by magic of Mahound out of seasand and the air by a warlock with his breath that he blares into them like to bubbles. And full fair cheer and rich was on the board that no wight could devise a fuller ne richer. And there was a vat of silver that was moved by craft to open in the which lay strange fishes withouten heads though misbelieving men nie that this be possible thing without they see it natheless they are so. And these fishes lie in an oily water brought there from Portugal land because of the fatness that therein is like to the juices of the olive press. And also it was marvel to see in that castle how by magic they make a compost out of fecund wheat kidneys out of Chaldee that by aid of certain angry spirits that they do into it swells up wondrously like to a vast mountain. And they teach the serpents there to entwine themselves up on long sticks out of the ground and of the scales of these serpents they brew out a brewage like to mead.

And the learning knight let pour for childe Leopold a draught and halp thereto the while all they that were there drank every each. And childe Leopold did up his beaver for to pleasure him and took apertly somewhat in amity for he never drank no manner of mead which he then put by and anon full privily he voided the more part in his neighbour glass and his neighbour wist not of his wile. And he sat down in that castle with them for to rest him there awhile. Thanked be Almighty God.`

export { backgroundText };
